### ISSUE TITLE
Python==2.7.5 in requirements.txt wil never pass

### ISSUE THREAD

**Issue by antonyho** [dangtrinhnt/gdm#1]
`pip install` can't handle Python installation. And Debian has no Python 2.7.5 package.

```
  Could not find a version that satisfies the requirement Python==2.7.5 (from -r requirements.txt (line 1)) (from versions: )
```

Shall that line be removed from requirements.txt?

**Comment by dangtrinhnt** [comment]
Hi @antonyho. 

Thanks for the report. The requirements are the baseline in which I used to deploy GDM several years (2014) ago. Perhaps, those versions have been removed. I think you have to update and test it with the current version of all the packages.
